FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu18.04

# Setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -y tzdata

# Install ROS
RUN apt-get install -y dirmngr gnupg2 curl
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      python-rosdep \
      python-rosinstall \
      python-vcstools \
      ros-melodic-perception
RUN rosdep init
RUN rosdep update

# Install tools for development
RUN apt-get update && \
    apt-get install -y vim byobu

# Make catkin workspace
RUN mkdir -p /root/catkin_ws/src
WORKDIR /root/catkin_ws
# Build sgm_gpu
RUN git clone https://github.com/ActiveIntelligentSystemsLab/sgm_gpu_ros.git src/sgm_gpu_ros
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             catkin_make -DCMAKE_BUILD_TYPE=Release"

# Load ROS environment at docker exec bash
RUN echo "source /opt/ros/melodic/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc

# Set entrypoint to load catkin_ws at docker run
COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD [ "bash" ]

