version: "2.3"
services: 
  master:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_master
    command: roslaunch sgm_gpu test.launch
    runtime: nvidia
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - sgm_gpu_root:/root
      
volumes:
  sgm_gpu_root:

